ROUTINE = ROUTINE id ':' [VARS] BLOCK.

VARS = var id {',' id} ':' TYPE ';' {id {',' id} ':' TYPE ';'}.

TYPE = int | float.

BLOCK = '{' [STATEMENT {STATEMENT}] '}'.

STATEMENT = ASSIGNMENT | CONDITION | WRITING.

ASSIGNMENT = id '=' EXPRESION ';'.

WRITING = print '(' (EXPRESSION {EXPRESSION} | string) {',' (EXPRESSION {EXPRESSION} | string)} ')' ';'.

CONDITION = if '(' EXPRESSION ')' BLOQUE [else BLOQUE] ';'.

EXPRESSION = EXP [('<' | '>' | '<>') EXP].

EXP = TERM {('+' | '-') TERM}.

TERM = (FACTOR) {('*' | '/') FACTOR}.

FACTOR = ('(' EXPRESSION ')') | (['+' | '-'] CONS_VAR).

CONS_VAR = id | cons_int | cons_float.